# Generated by Django 4.2.7 on 2026-05-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttritionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('top_factors', models.JSONField(blank=True, default=list)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_predictions', to='employees.employee')),
            ],
            options={
                'ordering': ['-prediction_date'],
                'get_latest_by': 'prediction_date',
            },
        ),
    ]
