# Generated by Django 4.2.7 on 2026-05-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('head_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=10)),
                ('job_role', models.CharField(max_length=100)),
                ('job_level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('years_at_company', models.IntegerField(default=0)),
                ('years_in_current_role', models.IntegerField(default=0)),
                ('years_since_last_promotion', models.IntegerField(default=0)),
                ('years_with_curr_manager', models.IntegerField(default=0)),
                ('num_companies_worked', models.IntegerField(default=1)),
                ('total_working_years', models.IntegerField(default=0)),
                ('training_times_last_year', models.IntegerField(default=0)),
                ('distance_from_home', models.IntegerField(default=5)),
                ('monthly_income', models.IntegerField(default=50000)),
                ('percent_salary_hike', models.IntegerField(default=10)),
                ('education', models.IntegerField(choices=[(1, 'Below College'), (2, 'College'), (3, 'Bachelor'), (4, 'Master'), (5, 'Doctor')], default=3)),
                ('job_satisfaction', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')], default=3)),
                ('environment_satisfaction', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')], default=3)),
                ('relationship_satisfaction', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')], default=3)),
                ('work_life_balance', models.IntegerField(choices=[(1, 'Bad'), (2, 'Good'), (3, 'Better'), (4, 'Best')], default=3)),
                ('performance_rating', models.IntegerField(choices=[(1, 'Low'), (2, 'Good'), (3, 'Excellent'), (4, 'Outstanding')], default=3)),
                ('business_travel', models.CharField(choices=[('Non-Travel', 'Non-Travel'), ('Travel_Rarely', 'Travel Rarely'), ('Travel_Frequently', 'Travel Frequently')], default='Travel_Rarely', max_length=30)),
                ('overtime', models.BooleanField(default=False)),
                ('attendance_percentage', models.FloatField(default=95.0)),
                ('hire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(max_length=50)),
                ('generated_review', models.TextField()),
                ('final_review', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BurnoutAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_text', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('burnout_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('week_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burnout_assessments', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'week_number', 'year')},
            },
        ),
    ]
